---
title: "PLACEHOLDER"
output:
  html_document:
    toc: true
    theme: united
chunk_output_type: console
editor_options: 
  chunk_output_type: console
---
# Continuous Results for Summaries

```{r contresults2, echo = FALSE, message = FALSE,warning=F, fig.width=8,fig.height=6, results='asis'}
dir.create("./all_outputs", showWarnings=F)
if(any(contDVs!="")){
     out<-list()
     outdat<-list()
     x<-1
     for(n in 1:length(subgroups)){
          grpcat<-ifelse(subgroups[n]=="", "Full Sample", subgroups[n])
          cat(sprintf("## %s\n\n", grpcat))
          cat("\n\n")
          
             for(i in 1:length(contDVs)){
                     
                  ph<-mydata[!is.na(mydata[contDVs[i]]),]
                     out[[x]]<-TreatmentEffects(ph, treats=treatment, 
                                     DV=contDVs[i], 
                                     model="linear",
                                    controls=covariates,
                                     sims=sims,
                                    subgroups = subgroups[n],
                                    comb="perm",
                                    clust=clust)
                     
                     outnames<-paste0("DV: ", contDVs[i])
                     cat(sprintf("### %s\n\n", outnames))
                     print(out[[x]][[4]])
                     cat("\n\n\n[Back to Table of Contents](#TOC)\n\n")
                     
                     outdat[[x]]<-out[[x]][[2]]
                     rownames(outdat[[x]])<-NULL
                     if(!any(names(outdat[[x]])=="group")){
                          outdat[[x]]$group<-"Full Sample"
                          outdat[[x]]<-outdat[[x]][c("min", "med", "max", "group", "treat", "conf", "signif_dif", "DV")]
                     }
                     outdat[[x]]$grpcat<-grpcat
                     
                     x<-x+1
             }
          
     }
     outdat1<-do.call(rbind, outdat)
} 
```

# Binary Results for Summaries

```{r binresults, echo = FALSE, message = FALSE,warning=F, fig.width=8,fig.height=6, results='asis'}
dir.create("./all_outputs", showWarnings=F)
if(any(binDVs!="")){
     out<-list()
     outdat<-list()
     x<-1
     for(n in 1:length(subgroups)){
          grpcat<-ifelse(subgroups[n]=="", "Full Sample", subgroups[n])
          cat(sprintf("## %s\n\n", grpcat))
          cat("\n\n")
          
             for(i in 1:length(binDVs)){
                  
                  ph<-mydata[!is.na(mydata[binDVs[i]]),]
     
                     out[[x]]<-TreatmentEffects(ph,
                                              treats=treatment,
                                     DV=binDVs[i],
                                     model="logit",
                                    controls=covariates,
                                     sims=sims,
                                    subgroups = subgroups[n],
                                    comb="perm",
                                    clust=clust)
                     outnames<-paste0("DV: ", binDVs[i])
                     cat(sprintf("### %s\n\n", outnames))
                     print(out[[x]][[4]])
                     cat("\n\n\n[Back to Table of Contents](#TOC)\n\n")
     
                    outdat[[x]]<-out[[x]][[2]]
                     rownames(outdat[[x]])<-NULL
                     if(!any(names(outdat[[x]])=="group")){
                          outdat[[x]]$group<-"Full Sample"
                          outdat[[x]]<-outdat[[x]][c("min", "med", "max", "group", "treat", "conf", "signif_dif", "DV")]
                     }
                     outdat[[x]]$grpcat<-grpcat
                     x<-x+1
                     }
     }
     outdat2<-do.call(rbind, outdat)
}

if(any(ls()=="outdat1") & any(ls()=="outdat2")){
     alldat<-rbind(outdat1, outdat2)
     write.csv(alldat, "./all_outputs/all_IDF_preds.csv")
}
if(any(ls()=="outdat1") & !any(ls()=="outdat2")){
     write.csv(outdat1, "./all_outputs/all_IDF_preds.csv")
} 
if(!any(ls()=="outdat1") & any(ls()=="outdat2")){
     write.csv(outdat2, "./all_outputs/all_IDF_preds.csv")
} 

```




















