---
title: "PLACEHOLDER"
output:
  html_document:
    toc: true
    theme: united
chunk_output_type: console
editor_options: 
  chunk_output_type: console
---
# Top-level results

```{r toplevel, echo = FALSE, message = FALSE,warning=F, fig.width=10,fig.height=7, results='asis'}

        if(all(colnames(dat)!=wt)){
                dat[ncol(dat)+1]<-1
                names(dat)[ncol(dat)]<-"noweight"
                wt<-"noweight"
        }

out<-XT(dat,DV, wt=wt, model=model)

dir.create("./all_outputs", showWarnings=F)

keeplist<-list()
for(i in 1:length(out)){
               grpcat<-DV[i]
               base::cat(sprintf("## %s\n\n", grpcat))
               base::cat("\n\n")
               
               out[[i]]$Var1<-out[[i]]$Var1 %>% ordered(.,out[[i]]$Var1)
               
             p<-ggplot(out[[i]], aes(x=Var1, y=value))+
                geom_bar(position="dodge", stat="identity")+
                theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                labs(x="",
                     y="Prop.")+
                theme_minimal()+
                scale_x_discrete(labels = function(x) str_wrap(x, width = 10))+
                geom_text(aes(label=round(value,2)),
            position = position_dodge(width = .9), show.legend=T, vjust=1.5)
        print(p)
        
        keep<-cbind(names(out)[i], out[[i]])
        names(keep)[1:2]<-c("DV", "answer_level")
        keep$answer_level<-keep$answer_level %>% as.character
        keep[nrow(keep)+1,]<-c(grpcat, "N Total=", sum(dat[wt]))
        keeplist[[i]]<-keep
        
        base::cat("\n\n\n[Back to Table of Contents](#TOC)\n\n")
}

```

# Results by subgroups

```{r subgroups, echo = FALSE, message = FALSE,warning=F, fig.width=10,fig.height=7, results='asis'}
if(any(subgroups!="")){
     out<-XT(dat,DV=DV, subgroups=subgroups, wt=wt, model=model)
     
     allkeep<-list()
     for(i in 1:length(out)){
          keeplist2<-list()
          grpcat<-names(out)[i]
          base::cat(sprintf("## %s\n\n", grpcat))
          base::cat("\n\n")
          for(n in 1:length(out[[i]])){
               ph<-out[[i]][[n]] %>% melt(id="Var1")
               ph$Var1<-ph$Var1 %>% ordered(.,sort(unique(ph$Var1)))
               ph$value<-ph$value %>% as.numeric
               sb<-names(out[[i]])[n] %>% strsplit("_X_") %>% unlist
               sb<-sb[2]
               
               base::cat(sprintf("### %s\n\n", sb))
               base::cat("\n\n")
               
               p<-ggplot(ph, aes(x=Var1, y=value, fill=variable))+
                     geom_bar(position="dodge", stat="identity")+
                     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                     labs(x="",
                          y="Prop.",
                          fill=sb,
                          title=paste0(grpcat, " X ", sb))+
                     theme_minimal()+
                     scale_x_discrete(labels = function(x) str_wrap(x, width = 10))+
                     geom_text(aes(label=round(value,2)),
                 position = position_dodge(width = .9), show.legend=F, vjust=1.5)
             print(p)
             
             keep<-cbind(grpcat, out[[i]][n][[1]])
             
             ph<-questionr::wtd.table(x=dat[,sb], weights=dat[,wt])
             ph<-ph[colnames(keep)[-1:-2]]
             
             colnames(keep)[-1:-2]<-paste0(sb, "_",colnames(keep)[-1:-2])
             
             names(keep)[1:2]<-c("DV", "answer_level")
             keep$answer_level<-keep$answer_level %>% as.character
             keep[nrow(keep)+1,]<-c(grpcat, "N Total=", ph)
             keeplist2[[n]]<-keep
             base::cat("\n\n\n[Back to Table of Contents](#TOC)\n\n")
          }
          keeplist3<-keeplist2[[1]]
          for(n in 2:length(keeplist2)){
               keeplist3<-merge(keeplist3, keeplist2[[n]], by.x=c("DV", "answer_level"), by.y=c("DV", "answer_level"))
          }
          
          allkeep[[i]]<-keeplist3
     }
     
     finalkeep<-list()
     for(i in 1:length(keeplist)){
          names(keeplist[[i]])[names(keeplist[[i]])=="value"]<-"Full_Sample"
          finalkeep[[i]]<-merge(keeplist[[i]], allkeep[[i]], by.x=c("DV", "answer_level"), by.y=c("DV", "answer_level"))
     }
}

if(any(subgroups!="")){
     finalkeep<-do.call(rbind, finalkeep)
     
     write.csv(finalkeep, paste0("./all_outputs/", "PLACEHOLDER", ".csv"))
}else{
     keeplist<-do.call(rbind, keeplist)
     write.csv(keeplist, paste0("./all_outputs/", "PLACEHOLDER", ".csv"))
}



```



